"""
Pydantic v2 schemas for the AI assistant POST /ask endpoint.
"""
from typing import Optional

from pydantic import BaseModel, Field


class AskRequest(BaseModel):
    """Request body for POST /ask."""

    question: str = Field(
        ...,
        min_length=5,
        max_length=1000,
        description="Natural language question about customer data.",
        examples=[
            "Why is customer C102 at high churn risk?",
            "Which plan has the highest churn rate?",
            "Show me the top 5 customers by monthly spend.",
            "What is the average satisfaction score for churned customers?",
        ],
    )

    # Optional: caller can hint a customer ID to skip regex detection
    customer_id: Optional[str] = Field(
        None,
        description="Optional explicit customer ID to scope the question to.",
        examples=["C102", "C045"],
    )


class AskResponse(BaseModel):
    """Response from POST /ask."""

    answer: str = Field(..., description="Natural language answer generated by Gemini.")

    sql_used: Optional[str] = Field(
        None,
        description=(
            "The SQL query generated and executed by the SQL agent to answer "
            "the question. None if the answer was built from pre-fetched context."
        ),
    )

    sources: list[str] = Field(
        default_factory=list,
        description=(
            "Data sources consulted to build the answer. "
            "Examples: 'customer_profile:C102', 'sql_agent:dynamic', 'analytics:summary'."
        ),
    )
